appname = comisiones_mid
httpport = ${COMISIONES_MID_HTTPPORT}
runmode = ${COMISIONES_MID_RUNMODE}
EnableDocs = ${COMISIONES_MID_ENABLEDOCS}
copyrequestbody = ${COMISIONES_MID_COPYREQUESTBODY}
xray = ${COMISIONES_MID_XRAY}

UrlTercerosCrud = ${COMISIONES_MID_TERCEROS}
UrlComisionesCrud = ${COMISIONES_MID_COMISIONES_CRUD}
UrlDocumentos = ${COMISIONES_MID_DOCUMENTOS_CRUD}
