appname = comisiones_mid
httpport = ${COMISIONES_MID_HTTPPORT}
runmode = ${COMISIONES_MID_RUNMODE||dev}
copyrequestbody = true

UrlTercerosCrud = ${COMISIONES_MID_TERCEROS}
UrlComisionesCrud = ${COMISIONES_MID_COMISIONES_CRUD}
UrlDocumentos = ${COMISIONES_MID_DOCUMENTOS_CRUD}
UrlGestorDocumental = ${COMISIONES_MID_GESTORDOCUMENTAL}
UrlCoordinadorUsuario = ${COMISIONES_MID_COORDINADOR_USUARIO}
UrlSecretariaAcademica = ${COMISIONES_MID_SECRETARIA_ACADEMICA}