appname = .
httpport = 8081
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

UrlTercerosCrud = ${COMISIONES_MID_V1_TERCEROS}
UrlComisionesCrud = ${COMISIONES_MID_V1_COMISIONES_CRUD}
UrlDocumentos = ${COMISIONES_MID_V1_DOCUMENTOS}